-- MySQL Script generated by MySQL Workbench
-- Fri May  3 23:45:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`region` (
  `idregion` INT NOT NULL AUTO_INCREMENT,
  `reg_desc` VARCHAR(255) NULL,
  PRIMARY KEY (`idregion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nivel` (
  `idnivel` INT NOT NULL AUTO_INCREMENT,
  `nivel_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`idnivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombreusuario` VARCHAR(255) NULL,
  `apellidousuario` VARCHAR(255) NULL,
  `contrausuario` VARCHAR(45) NULL,
  `mailusuario` VARCHAR(255) NULL,
  `nacimiento` DATE NULL,
  `region_idregion` INT NOT NULL,
  `nivel_idnivel` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `region_idregion`, `nivel_idnivel`),
  INDEX `fk_usuario_region_idx` (`region_idregion` ASC) VISIBLE,
  INDEX `fk_usuario_nivel1_idx` (`nivel_idnivel` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_region`
    FOREIGN KEY (`region_idregion`)
    REFERENCES `mydb`.`region` (`idregion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_nivel1`
    FOREIGN KEY (`nivel_idnivel`)
    REFERENCES `mydb`.`nivel` (`idnivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mentor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mentor` (
  `idmentor` INT NOT NULL AUTO_INCREMENT,
  `nombrementor` VARCHAR(255) NULL,
  `apellidomentor` VARCHAR(255) NULL,
  `mailmentor` VARCHAR(255) NULL,
  `contramentor` VARCHAR(45) NULL,
  `n3` TINYINT NULL,
  `n4opcion` TINYINT NULL,
  `n4desc` VARCHAR(255) NULL,
  `n5opcion` TINYINT NULL,
  `n5desc` VARCHAR(255) NULL,
  `region_idregion` INT NOT NULL,
  PRIMARY KEY (`idmentor`, `region_idregion`),
  INDEX `fk_mentor_region1_idx` (`region_idregion` ASC) VISIBLE,
  CONSTRAINT `fk_mentor_region1`
    FOREIGN KEY (`region_idregion`)
    REFERENCES `mydb`.`region` (`idregion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profesion` (
  `idprofesion` INT NOT NULL AUTO_INCREMENT,
  `profesion_desc` VARCHAR(255) NULL,
  PRIMARY KEY (`idprofesion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`feedback_m`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`feedback_m` (
  `idfeedback_m` INT NOT NULL AUTO_INCREMENT,
  `feedback_desc` VARCHAR(255) NULL,
  `usuario_idusuario` INT NOT NULL,
  `mentor_idmentor` INT NOT NULL,
  PRIMARY KEY (`idfeedback_m`, `usuario_idusuario`, `mentor_idmentor`),
  INDEX `fk_feedback_m_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_feedback_m_mentor1_idx` (`mentor_idmentor` ASC) VISIBLE,
  CONSTRAINT `fk_feedback_m_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feedback_m_mentor1`
    FOREIGN KEY (`mentor_idmentor`)
    REFERENCES `mydb`.`mentor` (`idmentor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`videos` (
  `idvideos` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NULL,
  `nivel_idnivel` INT NOT NULL,
  `profesion_idprofesion` INT NOT NULL,
  PRIMARY KEY (`idvideos`, `nivel_idnivel`, `profesion_idprofesion`),
  INDEX `fk_videos_nivel1_idx` (`nivel_idnivel` ASC) VISIBLE,
  INDEX `fk_videos_profesion1_idx` (`profesion_idprofesion` ASC) VISIBLE,
  CONSTRAINT `fk_videos_nivel1`
    FOREIGN KEY (`nivel_idnivel`)
    REFERENCES `mydb`.`nivel` (`idnivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videos_profesion1`
    FOREIGN KEY (`profesion_idprofesion`)
    REFERENCES `mydb`.`profesion` (`idprofesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profesion_has_mentor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profesion_has_mentor` (
  `profesion_idprofesion` INT NOT NULL,
  `mentor_idmentor` INT NOT NULL,
  `mentor_region_idregion` INT NOT NULL,
  PRIMARY KEY (`profesion_idprofesion`, `mentor_idmentor`, `mentor_region_idregion`),
  INDEX `fk_profesion_has_mentor_mentor1_idx` (`mentor_idmentor` ASC, `mentor_region_idregion` ASC) VISIBLE,
  INDEX `fk_profesion_has_mentor_profesion1_idx` (`profesion_idprofesion` ASC) VISIBLE,
  CONSTRAINT `fk_profesion_has_mentor_profesion1`
    FOREIGN KEY (`profesion_idprofesion`)
    REFERENCES `mydb`.`profesion` (`idprofesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesion_has_mentor_mentor1`
    FOREIGN KEY (`mentor_idmentor` , `mentor_region_idregion`)
    REFERENCES `mydb`.`mentor` (`idmentor` , `region_idregion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_has_videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_has_videos` (
  `usuario_idusuario` INT NOT NULL,
  `usuario_region_idregion` INT NOT NULL,
  `videos_idvideos` INT NOT NULL,
  `videos_nivel_idnivel` INT NOT NULL,
  `videos_profesion_idprofesion` INT NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `usuario_region_idregion`, `videos_idvideos`, `videos_nivel_idnivel`, `videos_profesion_idprofesion`),
  INDEX `fk_usuario_has_videos_videos1_idx` (`videos_idvideos` ASC, `videos_nivel_idnivel` ASC, `videos_profesion_idprofesion` ASC) VISIBLE,
  INDEX `fk_usuario_has_videos_usuario1_idx` (`usuario_idusuario` ASC, `usuario_region_idregion` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_videos_usuario1`
    FOREIGN KEY (`usuario_idusuario` , `usuario_region_idregion`)
    REFERENCES `mydb`.`usuario` (`idusuario` , `region_idregion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_videos_videos1`
    FOREIGN KEY (`videos_idvideos` , `videos_nivel_idnivel` , `videos_profesion_idprofesion`)
    REFERENCES `mydb`.`videos` (`idvideos` , `nivel_idnivel` , `profesion_idprofesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;